Ingredient.create(name: 'lemon')
Ingredient.create(name: 'ice')
Ingredient.create(name: 'Light rum')
Ingredient.create(name: 'Applejack')
Ingredient.create(name: 'Gin')
Ingredient.create(name: 'Dark rum')
Ingredient.create(name: 'Sweet Vermouth')
Ingredient.create(name: 'Triple sec')
Ingredient.create(name: 'Southern Comfort')
Ingredient.create(name: 'Orange bitters')
Ingredient.create(name: 'Amaretto')
Ingredient.create(name: 'Coffee liqueur')
Ingredient.create(name: 'Bourbon')
Ingredient.create(name: 'Tequila')
Ingredient.create(name: 'Vodka')
Ingredient.create(name: 'Kahlua')
Ingredient.create(name: 'Dubonnet Rouge')
Ingredient.create(name: 'Kahlua')
Ingredient.create(name: 'Irish whiskey')
Ingredient.create(name: 'Lime')
Ingredient.create(name: 'Tomato juice')
Ingredient.create(name: 'Egg')
Ingredient.create(name: 'Carbonated water')
Ingredient.create(name: 'Tonic')
Cocktail.create(name: 'Bloody Mary')
